---


---

<h1 id="흐름제어_흐름의-중단과-반환">흐름제어_흐름의 중단과 반환</h1>
<blockquote>
<p>return, break, continue, try~catch | Java와 거의 똑같다고 보면 됨</p>
</blockquote>
<h2 id="return문">return문</h2>
<p>값을 반환하는 데 사용. <strong>return 이후의 코드는 실행되지 않는다</strong></p>
<h3 id="return으로-unit반환하기">return으로 Unit반환하기</h3>
<p>Unit는 자바의 void와 비슷하지만, 코틀린의 Unit이란 반환하는 값이 아예 없는 게 아니라, Unit이라는 자료형 자체를 반환한다는 것을 뜻함.<br>
아래의 세 코드는 모두 동일한 결과를 반환함</p>
<pre><code>#Unit을 명시적으로 변환하는 케이스
fun hello(name: String): Unit{
	println(name)
	return Unit
}
</code></pre>
<pre><code>#Unit 이름을 생략하는 케이스
fun hello(name: String): Unit{
	println(name)
	return
}
</code></pre>
<pre><code>#Return문 자체를 생략하는 케이스
fun hello(name: String){
	println(name)
}
</code></pre>
<h3 id="람다식에서-return-사용하기">람다식에서 return 사용하기</h3>
<p>Inline으로 선언하지 않은 람다식에서는, return@label 과 같이 앳(@)과 라벨을 이용하여 return을 사용할 수 있음. 특히 인라인 함수에서 return을 사용할 경우, 비지역 반환으로 이어질 수 있으므로 라벨과 함께 return을 사용하면 좋다.</p>
<p>아래와 같이 사용한다.</p>
<pre><code>람다식 함수 이름 라벨 이름@ {
	...
	return@라벨 이름
}
</code></pre>
<p>예제: <a href="https://github.com/Walkers15/Kotlin/blob/master/NoInlineLambdaReturn.kt">라벨을 이용한 람다식의 변환</a></p>
<p>람다식의 표현식 블록에 직접 라벨을 쓰지 않고, 람다식의 명칭을 그대로 라벨처럼 사용할 수 있는데, 이것을 암묵적 라벨이라고 부른다.</p>
<h3 id="익명-함수를-사용한-반환">익명 함수를 사용한 반환</h3>
<p>람다식과 같이, 익명 함수도 사용할 수 있다. 이 때는 라벨을 사용하지 않고도 가까운 익명 함수 자체가 반환된다.</p>
<pre><code>#두 방법 모두 같은 결과를 출력한다.

##람다식 방법
val getMessage = lambda@ { num: Int -&gt;
	if(num !in 1..100) return@lambda "Error"
	"Success"
}

##익명 함수 방법
val getMessage = fun(num:Int): String {
	if(num !in 1..100) return "Error"
	return "Success"
}
</code></pre>
<p>보통의 경우에는 람다식을 사용하고, 명시적으로 반환해야 할 것이 여러 개라면 익명 함수를 쓰는 것이 좋다.</p>
<h2 id="break문과-continue문">break문과 continue문</h2>
<p><strong>break</strong>는 반복문 안의 해당 키워드를 사용한 지점에서 루프를 빠져나온다.<br>
<strong>continue</strong>는, 이후 본문을 건너 뛰고 조건을 검사한다.<br>
break, continue에도 @label을 붙여 반복문이 중단되고, 재개되는 위치를 바꿀 수 있음</p>
<pre><code>#예제_라벨을 이용한 흐름 변환

fun labelContinue(){
	println("labelContinue")
	first@ for(i in 1..5){&lt;---------------ㄱ
		for(j in 1..5){                   ㅣ
			if(j == 3) continue@first ----」
			println("i: $i, j: $j")
		}
	}
	println("after for i")
}
//result : (1,1),(1,2),(2,1),(2,2),(3,1),(3,2),(4,1)...
</code></pre>
<h2 id="예외-처리">예외 처리</h2>
<blockquote>
<p>프로그램 코드를 작성하다 보면 OS의 문제, 입력값의 문제 등으로 컴파일러가 잡아낼 수 없는 오류가 발생하여 프로그램이 중단하는 경우가 발생하는데, 이런 예외 상황에 미리 대비하는 것을 예외 처리라고 한다.</p>
</blockquote>
<p>try - catch 블록을 사용하여 예외를 처리할 수 있다. 다음과 같이 사용한다.</p>
<pre><code>try{
	예외 발생 가능성 있는 문장
} catch (e: 예외 클래스 이름){
	예외상황에서 처리하는 문장
} finally{
	반드시 실행되어야 하는 문장 //생략 가능
}
</code></pre>
<h3 id="특정-예외-처리">특정 예외 처리</h3>
<p>특정 예외를 처리하고 싶은 경우, 예외 클래스 이름에 특정 예외의 클래스명을 적는다. 특정 예외의 종류로는 ArithmeticException, IOException, ClassNotFoundExeption 등이 있다.</p>
<pre><code>#예시
catch(e : ArithmeticException){
	println("Exception is handled. ${e.message}")
}
//0으로 나눈 경우
//Exception is handled. / by zero
</code></pre>
<h3 id="스택의-추적">스택의 추적</h3>
<p>자바와 같이 printStackTrace() 를 사용한다.<br>
이 메소드를 사용하면,  예외의 종류와 예외가 발생한 위치를 확인할 수 있다.</p>
<pre><code>...
}catch(e: Exception) {
	e.printStackTrace();
}
...
</code></pre>
<h3 id="예외-발생시키기">예외 발생시키기</h3>
<p>try-catch문을 이용하는 등의 이유로, 사용자가 직접 예외를 발생시킬 수 있다<br>
<strong>throw</strong>키워드를 사용한다.</p>
<pre><code>throw Exception(message: String)
</code></pre>
<p>의 형태로 사용한다. <a href="https://github.com/Walkers15/Kotlin/blob/master/CustonExceptionText.md">예시 링크</a></p>
<h3 id="사용자-정의-예외">사용자 정의 예외</h3>
<p>기존 Exception 클래스로부터 새롭게 정의한 예외 클래스를 만들어 낼 수 있다.</p>
<pre><code>class &lt;사용자 예외 클래스 이름&gt;(message: String) : Exception(message)
</code></pre>
<p>의 형태로 정의하여 사용한다. <a href="https://github.com/Walkers15/Kotlin/blob/master/CustonExceptionText.md">예시 링크</a><br>
<a href="https://regexr.com/">정규식 관련 참조 링크</a></p>

